### ISSUE TITLE
How to build for Windows

### ISSUE THREAD

**Issue by arturlins** [x42/phaserotate.lv2#5]
Hi, thank you for your great work in x42 plugins.

I need some help in how to build the static binaries to be used on Windows (specially the CLI). I am using Windows 11, with Arch Linux via WSL2 and mingw64 for crosscompile. But with the instructions provided I can only build for Linux.

I am trying to use this code:
git clone https://github.com/x42/phaserotate.lv2.git
cd phaserotate.lv2
make submodules
make XWIN=x86_64-w64-mingw32

But it never compiles the Windows static binaries. Any help on how I could do it would be very appreciated.

**Comment by x42** [comment]
The problem with the CLI is that mingw still lacks std::thread support.
Chances are that https://github.com/meganz/mingw-std-threads works, but I have not investigated this.

However, the CLI `phase-rotate.cc` should build just fine with MSVC using `fftw3` and `libsndfile` from https://vcpkg.io

**Comment by arturlins** [comment]
Thank you for the answer! I will try to build via MSVC with the libraries and report back here the result (may take some time, I am not a programmer and will need to make some search).

**Comment by arturlins** [comment]
I was able to build the CLI via Cygwin. In futures updates would be really nice if the bulit CLI could be included in the installer. Thanks
